apiVersion: v1
kind: Secret
metadata:
  name: exportarr-secrets
  namespace: arr-exporter
stringData:
  # Api Keys are obtained in the respective applications. We will find a way to inject this information a configmap using other tools like Helm.
  SONARR_API_KEY: ""
  RADARR_API_KEY: ""
  PROWLARR_API_KEY: ""
