apiVersion: v1
kind: ConfigMap
metadata:
  name: exportarr-config
  namespace: arr-exporter
data:
  # Here you will see env variables. They are hardcoded but are generic.
  SONARR_URL: "http://sonarr.default.svc.cluster.local:8989/sonarr"
  RADARR_URL: "http://radarr.default.svc.cluster.local:7878/radarr"
  PROWLARR_URL: "http://prowlarr.default.svc.cluster.local:9696/prowlarr"
