apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: arr-exporter
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: 'exportarr-sonarr'
        static_configs:
          - targets: ['exportarr-sonarr.arr-exporter.svc.cluster.local:9707']
      - job_name: 'exportarr-radarr'
        static_configs:
          - targets: ['exportarr-radarr.arr-exporter.svc.cluster.local:9708']
      - job_name: 'exportarr-prowlarr'
        static_configs:
          - targets: ['exportarr-prowlarr.arr-exporter.svc.cluster.local:9709']
