apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-samba-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pi-samba-pv
  storageClassName: samba-nas
  resources:
    requests:
      storage: 50Gi
