apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
stringData:
  # If you want to pass in b64 encoded values instead, instead of `stringData`, use `data` and ensure the values are base64 encoded.
  username: ${USERNAME}
  password: ${PASSWORD}
